// ADMIN
export const SET_ADMIN = "SET_ADMIN";
export const LOGOUT_ADMIN = "LOGOUT_ADMIN";

// EMPLOYEE
export const SET_EMPLOYEE = "SET_EMPLOYEE";
export const GET_EMPLOYEES = "SET_EMPLOYEES";
export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const EMPLOYEE_CHECKIN = "EMPLOYEE_CHECKIN";
export const EMPLOYEE_CHECKOUT = "EMPLOYEE_CHECKOUT";
export const LOGOUT_EMPLOYEE = "LOGOUT_EMPLOYEE";